export const localhost = "http://localhost:8000/";

export const DECK_LIST_REQUEST = "DECK_LIST_REQUEST";
export const DECK_LIST_SUCCESS = "DECK_LIST_SUCCESS";
export const DECK_LIST_FAIL = "DECK_LIST_FAIL";

export const DECK_REQUEST = "DECK_REQUEST";
export const DECK_SUCCESS = "DECK_SUCCESS";
export const DECK_FAIL = "DECK_FAIL";

export const DECK_DELETE_REQUEST = "DECK_DELETE_REQUEST";
export const DECK_DELETE_SUCCESS = "DECK_DELETE_SUCCESS";
export const DECK_DELETE_FAIL = "DECK_DELETE_FAIL";

export const DECK_CREATE_REQUEST = "DECK_CREATE_REQUEST"
export const DECK_CREATE_SUCCESS = "DECK_CREATE_SUCCESS"
export const DECK_CREATE_FAIL = "DECK_CREATE_FAIL"

export const CARDS_OF_DECK_REQUEST = "CARDS_OF_DECK_REQUEST";
export const CARDS_OF_DECK_SUCCESS = "CARDS_OF_DECK_SUCCESS";
export const CARDS_OF_DECK_FAIL = "CARDS_OF_DECK_FAIL";

export const CARD_GET_ONE_REQUEST = "CARD_GET_ONE_REQUEST"
export const CARD_GET_ONE_SUCCESS = "CARD_GET_ONE_SUCCESS"
export const CARD_GET_ONE_FAIL = "CARD_GET_ONE_FAIL"

export const CARD_CREATE_REQUEST = "CARD_CREATE_REQUEST";
export const CARD_CREATE_SUCCESS = "CARD_CREATE_SUCCESS";
export const CARD_CREATE_FAIL = "CARD_CREATE_FAIL";

export const CARD_LEARN_REQUEST = "CARD_LEARN_REQUEST"
export const CARD_LEARN_SUCCESS = "CARD_LEARN_SUCCESS"
export const CARD_LEARN_FAIL = "CARD_LEARN_FAIL"

export const CARD_DECREASE_REQUEST = "CARD_DECREASE_REQUEST"
export const CARD_DECREASE_SUCCESS = "CARD_DECREASE_SUCCESS"
export const CARD_DECREASE_FAIL = "CARD_DECREASE_FAIL"

export const CARD_INCREASE_REQUEST = "CARD_INCREASE_REQUEST"
export const CARD_INCREASE_SUCCESS = "CARD_INCREASE_SUCCESS"
export const CARD_INCREASE_FAIL = "CARD_INCREASE_FAIL"

export const CARD_STATUS_REQUEST = "CARD_STATUS_REQUEST"
export const CARD_STATUS_SUCCESS = "CARD_STATUS_SUCCESS"
export const CARD_STATUS_FAIL = "CARD_STATUS_FAIL"

export const CARD_DELETE_REQUEST = "CARD_DELETE_REQUEST"
export const CARD_DELETE_SUCCESS = "CARD_DELETE_SUCCESS"
export const CARD_DELETE_FAIL = "CARD_DELETE_FAIL"